name: Continuous Integration
concurrency: ci-${{ github.ref }}
on:
  push:
    tags-ignore:
      - "*"
    branches:
      - "main"
  pull_request:
  release:
    types: [published]
  workflow_dispatch:

env:
  OBS_USER: ${{ secrets.OBS_USER }}
  OBS_PASS: ${{ secrets.OBS_PASS }}
  OBS_PROJECT: ${{ secrets.OBS_PROJECT}}

jobs:
  test-helm-charts:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: azure/setup-helm@v2.1
        with:
          version: v3.4.0
      - uses: actions/setup-python@v3
        with:
          python-version: 3.7
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.1
      - name: Lint
        run: ct lint --config=ct.yaml --lint-conf=helmlintconf.yaml

  build-static-binary:
    runs-on: ubuntu-20.04
    needs: [test-helm-charts]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: compress
        run: |
          set -x
          find ./charts/ -maxdepth 1 -mindepth 1 -exec sh -c 'tar -zcf $(basename {}).tgz -C charts/ ./$(basename {})/' \;
      - uses: actions/upload-artifact@v3
        with:
          name: charts
          path: |
            *.tgz

  release-rolling:
    needs: [test-helm-charts, build-static-binary]
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main')
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: charts
      - uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "rolling"
          prerelease: true
          title: "Cutting Edge"
          files: |
            trento-server.tgz

  release:
    runs-on: ubuntu-latest
    needs: [test-helm-charts]
    if: github.event.release
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Set up Helm
        uses: azure/setup-helm@v2.1
        with:
          version: v3.7.2

      - name: Add dependency chart repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_RELEASE_NAME_TEMPLATE: "{{ .Version }}"

  obs-commit:
    needs: [test-helm-charts]
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/main' || github.event_name == 'release'
    container:
      image: ghcr.io/trento-project/continuous-delivery:master
      env:
        GITHUB_OAUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEST_FOLDER: "/tmp/osc_project"
    strategy:
      matrix:
        charts: ["trento-server"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure OSC
        # OSC credentials must be configured beforehand as the HOME variables cannot be changed from /github/home
        # that is used to run osc commands
        run: |
          /scripts/init_osc_creds.sh
          mkdir -p $HOME/.config/osc
          cp /root/.config/osc/oscrc $HOME/.config/osc
      - name: Commit on OBS
        run: |
          echo "Installing helm and yq to run the makefile"
          ssl_verify=host zypper in -y helm wget
          wget https://github.com/mikefarah/yq/releases/download/3.4.1/yq_linux_amd64 -O /usr/bin/yq && chmod +x /usr/bin/yq
          echo "Commiting ${{ matrix.charts }} for package ${{ matrix.charts }}-helm"
          OBS_PACKAGE=$OBS_PROJECT/${{ matrix.charts }}-helm
          osc checkout $OBS_PACKAGE -o $DEST_FOLDER
          cp -r packaging/suse/${{ matrix.charts }}/* $DEST_FOLDER
          cp -r charts/${{ matrix.charts }}/Chart.yaml $DEST_FOLDER
          cd $DEST_FOLDER
          make
          osc ar
          osc commit -m "New development version of ${{ matrix.charts }}-helm released"
